//! Runtime stylesheet generation.
//!
//! One generator, driven entirely by a [`Palette`]. There are no hand-written
//! per-flavor stylesheets to drift out of sync, and nothing here knows the word
//! "Catppuccin" — a user-supplied theme renders through exactly this code path.
//!
//! # Why CSS custom properties and not `@define-color`
//!
//! libadwaita 1.6 moved its named colors from `@define-color` to CSS custom
//! properties on `:root` (verified against the installed libadwaita 1.9.2: it
//! exports `--window-bg-color`, `--sidebar-bg-color`, and friends). Overriding
//! only `@define-color` would parse without error and change nothing, because
//! libadwaita's own rules resolve `var(--window-bg-color)`. So the generator
//! emits custom properties as the real mechanism, and mirrors the handful of
//! legacy `@define-color` names afterwards for any third-party widget CSS that
//! still reads them.
//!
//! This module is GTK-free and returns a plain `String`, so the whole stylesheet
//! is unit-testable without a display.

use std::fmt::Write as _;

use super::palette::{Accent, Color, Palette};

/// Presentation choices that are not part of the palette itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StyleOptions {
    /// The UI accent: selection, focus rings, active sidebar row.
    pub accent: Accent,
    /// Draw client-side window rounding. Off by default — Hyprland already
    /// rounds windows, and libadwaita rounding on top of it reads as doubled.
    pub client_side_rounding: bool,
    /// Draw a client-side drop shadow. Off by default, same reason.
    pub client_side_shadow: bool,
    /// Mirrors `gtk-enable-animations`. When false the generator emits zero
    /// transition durations rather than relying on widgets to opt out.
    pub animations: bool,
}

impl Default for StyleOptions {
    fn default() -> Self {
        Self {
            accent: Accent::Mauve,
            client_side_rounding: false,
            client_side_shadow: false,
            animations: true,
        }
    }
}

/// Short transition, per the 120–180 ms budget. Nothing bouncy.
const TRANSITION_MS: u32 = 150;

/// Generate the complete stylesheet for `palette` under `options`.
pub fn generate(palette: &Palette, options: &StyleOptions) -> String {
    let n = &palette.neutrals;
    let accent = palette.accent(options.accent);
    let on_accent = palette.on_color(accent);
    let duration = if options.animations { TRANSITION_MS } else { 0 };

    // Shading direction depends on polarity: dark themes deepen toward crust,
    // Latte deepens toward its own darker neutrals. Using the ramp for both
    // means a light user theme shades correctly without special-casing.
    let shade = if palette.dark {
        n.crust.to_rgba(0.36)
    } else {
        n.overlay0.to_rgba(0.18)
    };
    let border = n.surface0.to_rgba(if palette.dark { 0.85 } else { 0.9 });

    let mut css = String::with_capacity(8 * 1024);

    css.push_str("/* Generated by Hive. Do not edit — regenerated on every theme change. */\n");
    let _ = writeln!(css, "/* theme: {} ({}) */\n", palette.id, palette.name);

    // ---- libadwaita named colors, as custom properties -------------------
    css.push_str(":root {\n");

    let mut prop = |name: &str, color: &str| {
        let _ = writeln!(css, "  --{name}: {color};");
    };

    prop("window-bg-color", &n.base.to_hex());
    prop("window-fg-color", &n.text.to_hex());
    prop("view-bg-color", &n.base.to_hex());
    prop("view-fg-color", &n.text.to_hex());

    // Header bar and sidebar sit one step back from the content surface, so the
    // regions separate by elevation rather than by border lines.
    prop("headerbar-bg-color", &n.mantle.to_hex());
    prop("headerbar-fg-color", &n.text.to_hex());
    prop("headerbar-border-color", &n.mantle.to_hex());
    prop("headerbar-backdrop-color", &n.mantle.to_hex());
    prop("headerbar-shade-color", &shade);
    prop("headerbar-darker-shade-color", &shade);

    prop("sidebar-bg-color", &n.mantle.to_hex());
    prop("sidebar-fg-color", &n.text.to_hex());
    prop("sidebar-backdrop-color", &n.mantle.to_hex());
    prop("sidebar-border-color", &border);
    prop("sidebar-shade-color", &shade);

    prop("secondary-sidebar-bg-color", &n.crust.to_hex());
    prop("secondary-sidebar-fg-color", &n.text.to_hex());
    prop("secondary-sidebar-backdrop-color", &n.crust.to_hex());
    prop("secondary-sidebar-border-color", &border);
    prop("secondary-sidebar-shade-color", &shade);

    prop("card-bg-color", &n.surface0.to_hex());
    prop("card-fg-color", &n.text.to_hex());
    prop("card-shade-color", &shade);

    prop("dialog-bg-color", &n.mantle.to_hex());
    prop("dialog-fg-color", &n.text.to_hex());

    prop("popover-bg-color", &n.surface0.to_hex());
    prop("popover-fg-color", &n.text.to_hex());
    prop("popover-shade-color", &shade);

    prop("thumbnail-bg-color", &n.surface0.to_hex());
    prop("thumbnail-fg-color", &n.text.to_hex());

    prop("overview-bg-color", &n.mantle.to_hex());
    prop("overview-fg-color", &n.text.to_hex());

    prop("active-toggle-bg-color", &n.surface1.to_hex());
    prop("active-toggle-fg-color", &n.text.to_hex());

    prop("shade-color", &shade);
    prop("border-color", &border);
    prop("scrollbar-outline-color", &n.base.to_rgba(0.5));
    prop("slider-border-color", &border);
    prop("banner-color", &n.surface0.to_hex());
    prop("standalone-color", &accent.to_hex());

    prop("accent-bg-color", &accent.to_hex());
    prop("accent-fg-color", &on_accent.to_hex());
    prop("accent-color", &accent.to_hex());

    let red = palette.accent(Accent::Red);
    let green = palette.accent(Accent::Green);
    let yellow = palette.accent(Accent::Yellow);
    prop("destructive-bg-color", &red.to_hex());
    prop("destructive-fg-color", &palette.on_color(red).to_hex());
    prop("destructive-color", &red.to_hex());
    prop("error-bg-color", &red.to_hex());
    prop("error-fg-color", &palette.on_color(red).to_hex());
    prop("error-color", &red.to_hex());
    prop("success-bg-color", &green.to_hex());
    prop("success-fg-color", &palette.on_color(green).to_hex());
    prop("success-color", &green.to_hex());
    prop("warning-bg-color", &yellow.to_hex());
    prop("warning-fg-color", &palette.on_color(yellow).to_hex());
    prop("warning-color", &yellow.to_hex());

    if !options.client_side_rounding {
        css.push_str("  --window-radius: 0;\n");
    }

    css.push_str("}\n\n");

    // ---- Legacy @define-color mirror -------------------------------------
    // Kept for third-party widget CSS that predates the custom-property switch.
    // libadwaita itself no longer reads these.
    css.push_str("/* Legacy named-color mirror (pre-1.6 consumers). */\n");
    for (name, color) in [
        ("window_bg_color", n.base),
        ("window_fg_color", n.text),
        ("view_bg_color", n.base),
        ("view_fg_color", n.text),
        ("headerbar_bg_color", n.mantle),
        ("headerbar_fg_color", n.text),
        ("sidebar_bg_color", n.mantle),
        ("sidebar_fg_color", n.text),
        ("card_bg_color", n.surface0),
        ("popover_bg_color", n.surface0),
        ("dialog_bg_color", n.mantle),
        ("accent_bg_color", accent),
        ("accent_fg_color", on_accent),
        ("accent_color", accent),
        ("theme_bg_color", n.base),
        ("theme_fg_color", n.text),
        ("theme_base_color", n.base),
        ("theme_text_color", n.text),
        ("theme_selected_bg_color", accent),
        ("theme_selected_fg_color", on_accent),
    ] {
        let _ = writeln!(css, "@define-color {name} {};", color.to_hex());
    }
    css.push('\n');

    // ---- Direct window background ---------------------------------------
    //
    // Setting `--window-bg-color` is not sufficient on its own. A system GTK
    // theme installed at ~/.config/gtk-4.0/gtk.css can declare
    // `window { background-color: ... }` outright, and a custom property never
    // overrides a direct declaration — it only feeds the rules that read it. So
    // the window background is stated explicitly here too.
    //
    // It is deliberately opaque. Hyprland already applies its own opacity, and
    // a translucent client background underneath it compounds into something
    // neither setting asked for — the same doubling-up argument as rounding and
    // shadow below.
    let _ = write!(
        css,
        "\
window.background,
window.background:backdrop {{
  background-color: {base};
  color: {text};
}}

",
        base = n.base.to_hex(),
        text = n.text.to_hex(),
    );

    // ---- Compositor ownership of rounding and shadow ---------------------
    if !options.client_side_rounding || !options.client_side_shadow {
        css.push_str("/* Hyprland owns rounding and shadow; avoid drawing them twice. */\n");
        css.push_str("window.csd,\nwindow.csd:backdrop {\n");
        if !options.client_side_shadow {
            css.push_str("  box-shadow: none;\n");
        }
        if !options.client_side_rounding {
            css.push_str("  border-radius: 0;\n");
        }
        css.push_str("}\n\n");
    }

    // ---- Hive's own widgets ----------------------------------------------
    let _ = write!(
        css,
        "\
/* Regions separate by elevation and spacing, not by lines. */
.hive-content {{
  background-color: {base};
}}

/* Thin status line: item count, selection count, free space. */
.hive-status-bar {{
  background-color: {mantle};
  color: {subtext0};
  font-size: 0.85em;
  padding: 4px 12px;
  min-height: 20px;
}}

.hive-status-bar .hive-status-segment {{
  padding: 0 2px;
}}

/* Small dim caps label above each sidebar group. */
.hive-section-label {{
  color: {subtext0};
  font-size: 0.8em;
  font-weight: 700;
  padding: 10px 12px 4px 12px;
}}

.hive-sidebar {{
  background-color: {mantle};
}}

.hive-sidebar row {{
  border-radius: 8px;
  margin: 1px 6px;
  min-height: 32px;
  transition: background-color {duration}ms ease-out;
}}

.hive-sidebar row:hover {{
  background-color: {surface0};
}}

.hive-sidebar row:selected {{
  background-color: {accent_soft};
  color: {text};
}}

.hive-sidebar row:selected image {{
  color: {accent};
}}

/* Breadcrumb: flat segments, one accent at a time. */
.hive-breadcrumb button {{
  padding: 2px 8px;
  min-height: 26px;
  border-radius: 6px;
  background: none;
  box-shadow: none;
  border: none;
  font-weight: normal;
  transition: background-color {duration}ms ease-out;
}}

.hive-breadcrumb button:hover {{
  background-color: {surface0};
}}

.hive-breadcrumb button.hive-breadcrumb-current {{
  font-weight: bold;
  color: {text};
}}

.hive-breadcrumb .hive-breadcrumb-separator {{
  color: {overlay0};
  padding: 0 1px;
}}

/* File pane. Generous row padding, no grid lines. */
.hive-file-pane {{
  background-color: {base};
}}

.hive-file-pane listview > row,
.hive-file-pane columnview > listview > row {{
  padding: 2px 4px;
  min-height: 30px;
  border-radius: 6px;
  transition: background-color {duration}ms ease-out;
}}

.hive-file-pane row:hover {{
  background-color: {surface0};
}}

.hive-file-pane row:selected {{
  background-color: {accent_soft};
  color: {text};
}}

.hive-file-pane columnview > header > button {{
  background: none;
  box-shadow: none;
  border: none;
  color: {subtext0};
  font-size: 0.9em;
  padding: 4px 8px;
}}

.hive-file-pane columnview > header > button:hover {{
  background-color: {surface0};
}}

.hive-file-name {{
  color: {text};
}}

.hive-file-meta {{
  color: {subtext0};
  font-size: 0.9em;
}}

.hive-file-symlink {{
  font-style: italic;
  color: {subtext0};
}}

/* Grid view cells. */
.hive-file-pane gridview > child {{
  padding: 8px;
  border-radius: 8px;
  transition: background-color {duration}ms ease-out;
}}

.hive-file-pane gridview > child:hover {{
  background-color: {surface0};
}}

.hive-file-pane gridview > child:selected {{
  background-color: {accent_soft};
}}

/* Placeholder shown while a directory is still enumerating or is empty. */
.hive-placeholder {{
  color: {overlay1};
}}

.hive-placeholder-icon {{
  color: {surface2};
}}

/* Default folder and file icons stay monochrome; folder colors override. */
.hive-item-icon {{
  color: {subtext1};
}}

.hive-folder-icon {{
  color: {subtext1};
}}
",
        base = n.base.to_hex(),
        mantle = n.mantle.to_hex(),
        surface0 = n.surface0.to_hex(),
        surface2 = n.surface2.to_hex(),
        overlay0 = n.overlay0.to_hex(),
        overlay1 = n.overlay1.to_hex(),
        subtext0 = n.subtext0.to_hex(),
        subtext1 = n.subtext1.to_hex(),
        text = n.text.to_hex(),
        accent = accent.to_hex(),
        // Selection is a wash of the accent rather than a solid fill, so the
        // label keeps the normal text color and only one accent reads at a time.
        accent_soft = accent.to_rgba(if palette.dark { 0.26 } else { 0.22 }),
        duration = duration,
    );

    // ---- Folder color classes -------------------------------------------
    // One class per accent slot, resolved through the active palette. This is
    // what makes a "mauve" folder Mocha-mauve in Mocha and Latte-mauve in Latte:
    // the stored value is the slot name, and the hex is regenerated per theme.
    css.push_str("\n/* Folder colors: tint the symbolic icon only. */\n");
    for slot in Accent::ALL {
        let _ = writeln!(
            css,
            ".hive-folder-icon.hive-accent-{}{{color:{};}}",
            slot.id(),
            palette.accent(slot).to_hex()
        );
    }

    css
}

/// Whether `color` needs a darker or lighter companion — exposed for callers
/// that tint outside CSS (icon paintables, for instance).
pub fn contrasting_text(palette: &Palette, background: Color) -> Color {
    palette.on_color(background)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::theme::catppuccin::{BUILT_IN, LATTE, MOCHA};

    fn opts(accent: Accent) -> StyleOptions {
        StyleOptions {
            accent,
            ..StyleOptions::default()
        }
    }

    #[test]
    fn braces_balance_for_every_flavor() {
        // The generator builds CSS with format!, where a stray `{` or `}` in a
        // literal silently produces a stylesheet GTK will reject at runtime.
        for palette in BUILT_IN {
            let css = generate(palette, &opts(Accent::Mauve));
            let opens = css.matches('{').count();
            let closes = css.matches('}').count();
            assert_eq!(opens, closes, "unbalanced braces in {}", palette.id);
            assert!(!css.contains("{{"), "unescaped brace in {}", palette.id);
            assert!(!css.contains("}}"), "unescaped brace in {}", palette.id);
        }
    }

    #[test]
    fn window_background_is_declared_directly_and_opaquely() {
        // A system GTK theme can declare `window { background-color: ... }`
        // outright; a custom property would not override that, so the generator
        // must state the background itself. And it must be a solid hex, not an
        // rgba() — client-side translucency compounds with the compositor's own.
        for palette in BUILT_IN {
            let css = generate(palette, &opts(Accent::Mauve));
            let expected = format!("background-color: {};", palette.neutrals.base.to_hex());
            assert!(
                css.contains("window.background") && css.contains(&expected),
                "{} lacks a direct opaque window background",
                palette.id
            );
        }
    }

    #[test]
    fn emits_custom_properties_not_only_define_color() {
        // Regression guard: libadwaita >= 1.6 resolves var(--window-bg-color).
        // A stylesheet that only sets @define-color parses fine and themes
        // nothing, which is exactly the failure this test exists to catch.
        let css = generate(&MOCHA, &opts(Accent::Mauve));
        assert!(css.contains("--window-bg-color: #1e1e2e;"));
        assert!(css.contains("--sidebar-bg-color: #181825;"));
        assert!(css.contains("--view-bg-color: #1e1e2e;"));
        assert!(css.contains(":root {"));
    }

    #[test]
    fn accent_choice_drives_accent_properties() {
        let mauve = generate(&MOCHA, &opts(Accent::Mauve));
        let green = generate(&MOCHA, &opts(Accent::Green));
        assert!(mauve.contains("--accent-bg-color: #cba6f7;"));
        assert!(green.contains("--accent-bg-color: #a6e3a1;"));
        assert_ne!(mauve, green);
    }

    #[test]
    fn every_flavor_produces_distinct_output() {
        let sheets: Vec<String> = BUILT_IN
            .iter()
            .map(|p| generate(p, &opts(Accent::Mauve)))
            .collect();
        for (i, a) in sheets.iter().enumerate() {
            for b in sheets.iter().skip(i + 1) {
                assert_ne!(a, b);
            }
        }
    }

    #[test]
    fn all_fourteen_folder_classes_are_emitted() {
        let css = generate(&MOCHA, &opts(Accent::Mauve));
        for slot in Accent::ALL {
            let class = format!(".hive-folder-icon.hive-accent-{}", slot.id());
            assert!(css.contains(&class), "missing {class}");
        }
    }

    #[test]
    fn folder_colors_follow_the_active_flavor() {
        // The same slot name must resolve to different hex per flavor — this is
        // the property that keeps folder colors correct across a flavor switch.
        let mocha = generate(&MOCHA, &opts(Accent::Blue));
        let latte = generate(&LATTE, &opts(Accent::Blue));
        assert!(mocha.contains(".hive-folder-icon.hive-accent-mauve{color:#cba6f7;}"));
        assert!(latte.contains(".hive-folder-icon.hive-accent-mauve{color:#8839ef;}"));
    }

    #[test]
    fn compositor_owns_rounding_and_shadow_by_default() {
        let css = generate(&MOCHA, &StyleOptions::default());
        assert!(
            css.contains("window.csd"),
            "decoration block should be emitted"
        );
        assert!(css.contains("--window-radius: 0;"));

        // Assert against the decoration block specifically. Searching the whole
        // stylesheet for "box-shadow: none" would also match the flat-button
        // rules and pass no matter what this option did.
        let block = decoration_block(&css).expect("decoration block");
        assert!(block.contains("box-shadow: none;"), "{block}");
        assert!(block.contains("border-radius: 0;"), "{block}");

        let csd = generate(
            &MOCHA,
            &StyleOptions {
                client_side_rounding: true,
                client_side_shadow: true,
                ..StyleOptions::default()
            },
        );
        assert!(!csd.contains("--window-radius: 0;"));
        assert!(
            decoration_block(&csd).is_none(),
            "no decoration overrides when the client draws them"
        );
    }

    #[test]
    fn rounding_and_shadow_can_be_enabled_independently() {
        let shadow_only = generate(
            &MOCHA,
            &StyleOptions {
                client_side_shadow: true,
                ..StyleOptions::default()
            },
        );
        let block = decoration_block(&shadow_only).expect("decoration block");
        assert!(!block.contains("box-shadow"), "{block}");
        assert!(block.contains("border-radius: 0;"), "{block}");

        let rounding_only = generate(
            &MOCHA,
            &StyleOptions {
                client_side_rounding: true,
                ..StyleOptions::default()
            },
        );
        let block = decoration_block(&rounding_only).expect("decoration block");
        assert!(block.contains("box-shadow: none;"), "{block}");
        assert!(!block.contains("border-radius"), "{block}");
    }

    /// Extract the `window.csd { … }` rule body, if the generator emitted one.
    fn decoration_block(css: &str) -> Option<&str> {
        let start = css.find("window.csd")?;
        let open = css[start..].find('{')? + start;
        let close = css[open..].find('}')? + open;
        Some(&css[open + 1..close])
    }

    #[test]
    fn disabling_animations_zeroes_durations() {
        let on = generate(&MOCHA, &StyleOptions::default());
        assert!(on.contains("150ms"));

        let off = generate(
            &MOCHA,
            &StyleOptions {
                animations: false,
                ..StyleOptions::default()
            },
        );
        assert!(!off.contains("150ms"));
        assert!(off.contains("0ms"));
    }

    #[test]
    fn light_theme_gets_readable_accent_foreground() {
        // Latte's crust and base are both light, so a polarity-based foreground
        // choice puts pale text on Latte's yellow accent. The generator must
        // emit the higher-contrast end of the ramp instead.
        use crate::theme::palette::contrast_ratio;

        let yellow = LATTE.accent(Accent::Yellow);
        let fg = LATTE.on_color(yellow);
        let css = generate(&LATTE, &opts(Accent::Yellow));
        assert!(css.contains(&format!("--accent-fg-color: {};", fg.to_hex())));

        assert!(
            contrast_ratio(fg, yellow) > contrast_ratio(LATTE.neutrals.base, yellow),
            "must beat the naive light-theme choice"
        );
        assert_eq!(fg, LATTE.neutrals.text, "the dark end of Latte's ramp");
    }

    #[test]
    fn dark_theme_gets_readable_accent_foreground() {
        use crate::theme::palette::contrast_ratio;

        let mauve = MOCHA.accent(Accent::Mauve);
        let fg = MOCHA.on_color(mauve);
        assert_eq!(fg, MOCHA.neutrals.crust, "dark text on a light accent");
        assert!(
            contrast_ratio(fg, mauve) > 4.5,
            "readable at body-text size"
        );
    }

    #[test]
    fn no_unresolved_format_placeholders_remain() {
        for palette in BUILT_IN {
            let css = generate(palette, &opts(Accent::Teal));
            assert!(
                !css.contains("{}"),
                "unfilled placeholder in {}",
                palette.id
            );
        }
    }

    #[test]
    fn contrasting_text_matches_palette_on_color() {
        let bg = MOCHA.accent(Accent::Peach);
        assert_eq!(contrasting_text(&MOCHA, bg), MOCHA.on_color(bg));
    }
}
