//! Runtime stylesheet generation.

use std::fmt::Write as _;

use super::palette::{Accent, Color, Palette};

/// Presentation choices that are not part of the palette itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StyleOptions {
    /// The UI accent: selection, focus rings, active sidebar row.
    pub accent: Accent,
    /// Draw client-side window rounding. Off by default; the compositor owns it.
    pub client_side_rounding: bool,
    /// Draw a client-side drop shadow. Off by default, same reason.
    pub client_side_shadow: bool,
    /// Mirrors `gtk-enable-animations`; when false, durations are emitted as zero.
    pub animations: bool,
}

impl Default for StyleOptions {
    fn default() -> Self {
        Self {
            accent: Accent::Mauve,
            client_side_rounding: false,
            client_side_shadow: false,
            animations: true,
        }
    }
}

/// Short transition, per the 120–180 ms budget. Nothing bouncy.
const TRANSITION_MS: u32 = 150;

/// Generate the complete stylesheet for `palette` under `options`.
pub fn generate(palette: &Palette, options: &StyleOptions) -> String {
    let n = &palette.neutrals;
    let accent = palette.accent(options.accent);
    let on_accent = palette.on_color(accent);
    let duration = if options.animations { TRANSITION_MS } else { 0 };

    let shade = if palette.dark {
        n.crust.to_rgba(0.36)
    } else {
        n.overlay0.to_rgba(0.18)
    };
    let border = n.surface0.to_rgba(if palette.dark { 0.85 } else { 0.9 });

    let mut css = String::with_capacity(8 * 1024);

    css.push_str("/* Generated by Hive. Do not edit — regenerated on every theme change. */\n");
    let _ = writeln!(css, "/* theme: {} ({}) */\n", palette.id, palette.name);

    // libadwaita >= 1.6 resolves var(--window-bg-color) rather than @define-color.
    // Setting only @define-color parses fine and themes nothing.
    css.push_str(":root {\n");

    let mut prop = |name: &str, color: &str| {
        let _ = writeln!(css, "  --{name}: {color};");
    };

    prop("window-bg-color", &n.base.to_hex());
    prop("window-fg-color", &n.text.to_hex());
    prop("view-bg-color", &n.base.to_hex());
    prop("view-fg-color", &n.text.to_hex());

    prop("headerbar-bg-color", &n.mantle.to_hex());
    prop("headerbar-fg-color", &n.text.to_hex());
    prop("headerbar-border-color", &n.mantle.to_hex());
    prop("headerbar-backdrop-color", &n.mantle.to_hex());
    prop("headerbar-shade-color", &shade);
    prop("headerbar-darker-shade-color", &shade);

    prop("sidebar-bg-color", &n.mantle.to_hex());
    prop("sidebar-fg-color", &n.text.to_hex());
    prop("sidebar-backdrop-color", &n.mantle.to_hex());
    prop("sidebar-border-color", &border);
    prop("sidebar-shade-color", &shade);

    prop("secondary-sidebar-bg-color", &n.crust.to_hex());
    prop("secondary-sidebar-fg-color", &n.text.to_hex());
    prop("secondary-sidebar-backdrop-color", &n.crust.to_hex());
    prop("secondary-sidebar-border-color", &border);
    prop("secondary-sidebar-shade-color", &shade);

    prop("card-bg-color", &n.surface0.to_hex());
    prop("card-fg-color", &n.text.to_hex());
    prop("card-shade-color", &shade);

    prop("dialog-bg-color", &n.mantle.to_hex());
    prop("dialog-fg-color", &n.text.to_hex());

    prop("popover-bg-color", &n.surface0.to_hex());
    prop("popover-fg-color", &n.text.to_hex());
    prop("popover-shade-color", &shade);

    prop("thumbnail-bg-color", &n.surface0.to_hex());
    prop("thumbnail-fg-color", &n.text.to_hex());

    prop("overview-bg-color", &n.mantle.to_hex());
    prop("overview-fg-color", &n.text.to_hex());

    prop("active-toggle-bg-color", &n.surface1.to_hex());
    prop("active-toggle-fg-color", &n.text.to_hex());

    prop("shade-color", &shade);
    prop("border-color", &border);
    prop("scrollbar-outline-color", &n.base.to_rgba(0.5));
    prop("slider-border-color", &border);
    prop("banner-color", &n.surface0.to_hex());
    prop("standalone-color", &accent.to_hex());

    prop("accent-bg-color", &accent.to_hex());
    prop("accent-fg-color", &on_accent.to_hex());
    prop("accent-color", &accent.to_hex());

    let red = palette.accent(Accent::Red);
    let green = palette.accent(Accent::Green);
    let yellow = palette.accent(Accent::Yellow);
    prop("destructive-bg-color", &red.to_hex());
    prop("destructive-fg-color", &palette.on_color(red).to_hex());
    prop("destructive-color", &red.to_hex());
    prop("error-bg-color", &red.to_hex());
    prop("error-fg-color", &palette.on_color(red).to_hex());
    prop("error-color", &red.to_hex());
    prop("success-bg-color", &green.to_hex());
    prop("success-fg-color", &palette.on_color(green).to_hex());
    prop("success-color", &green.to_hex());
    prop("warning-bg-color", &yellow.to_hex());
    prop("warning-fg-color", &palette.on_color(yellow).to_hex());
    prop("warning-color", &yellow.to_hex());

    if !options.client_side_rounding {
        css.push_str("  --window-radius: 0;\n");
    }

    css.push_str("}\n\n");

    css.push_str("/* Legacy named-color mirror (pre-1.6 consumers). */\n");
    for (name, color) in [
        ("window_bg_color", n.base),
        ("window_fg_color", n.text),
        ("view_bg_color", n.base),
        ("view_fg_color", n.text),
        ("headerbar_bg_color", n.mantle),
        ("headerbar_fg_color", n.text),
        ("sidebar_bg_color", n.mantle),
        ("sidebar_fg_color", n.text),
        ("card_bg_color", n.surface0),
        ("popover_bg_color", n.surface0),
        ("dialog_bg_color", n.mantle),
        ("accent_bg_color", accent),
        ("accent_fg_color", on_accent),
        ("accent_color", accent),
        ("theme_bg_color", n.base),
        ("theme_fg_color", n.text),
        ("theme_base_color", n.base),
        ("theme_text_color", n.text),
        ("theme_selected_bg_color", accent),
        ("theme_selected_fg_color", on_accent),
    ] {
        let _ = writeln!(css, "@define-color {name} {};", color.to_hex());
    }
    css.push('\n');

    let _ = write!(
        css,
        "\
window.background,
window.background:backdrop {{
  background-color: {base};
  color: {text};
}}

/* Concrete surfaces, not just custom properties.

   A hand-written system GTK theme — the kind installed as
   ~/.config/gtk-4.0/gtk.css — paints widgets with literal colours instead of
   reading libadwaita's `--view-bg-color` and friends. Hive's `:root` block is
   then simply never consulted, and no provider priority fixes that: the other
   stylesheet is not asking a question Hive can answer. So every surface gets a
   concrete declaration on the selector such a theme would target. Without
   these, a light flavor half-applies — the file pane keeps the system theme's
   dark background while everything around it turns light. */
.view,
iconview,
columnview,
listview,
gridview,
columnview > listview {{
  background-color: {base};
  color: {text};
}}

headerbar {{
  background-color: {mantle};
  color: {text};
}}

/* Header controls state their own colour too. Inheriting leaves them at the
   system theme's foreground, which against a light flavor's header renders
   pale-on-pale and effectively invisible. */
headerbar button,
headerbar button image,
headerbar button label,
headerbar menubutton > button image {{
  color: {text};
}}

headerbar button:disabled,
headerbar button:disabled image {{
  color: {overlay0};
}}

popover > contents {{
  background-color: {surface0};
  color: {text};
}}

popover > arrow {{
  background-color: {surface0};
}}

",
        base = n.base.to_hex(),
        text = n.text.to_hex(),
        mantle = n.mantle.to_hex(),
        surface0 = n.surface0.to_hex(),
        overlay0 = n.overlay0.to_hex(),
    );

    if !options.client_side_rounding || !options.client_side_shadow {
        css.push_str("/* Hyprland owns rounding and shadow; avoid drawing them twice. */\n");
        css.push_str("window.csd,\nwindow.csd:backdrop {\n");
        if !options.client_side_shadow {
            css.push_str("  box-shadow: none;\n");
        }
        if !options.client_side_rounding {
            css.push_str("  border-radius: 0;\n");
        }
        css.push_str("}\n\n");
    }

    let _ = write!(
        css,
        "\
/* Regions separate by elevation and spacing, not by lines. */
.hive-content {{
  background-color: {base};
}}

/* Thin status line: item count, selection count, free space. */
.hive-status-bar {{
  background-color: {mantle};
  color: {subtext0};
  font-size: 0.85em;
  padding: 4px 12px;
  min-height: 20px;
}}

.hive-status-bar .hive-status-segment {{
  padding: 0 2px;
}}

/* Small dim caps label above each sidebar group. */
.hive-section-label {{
  color: {subtext0};
  font-size: 0.8em;
  font-weight: 700;
  padding: 10px 12px 4px 12px;
}}

.hive-sidebar {{
  background-color: {mantle};
  color: {text};
}}

/* Sidebar text is stated rather than inherited: a hand-written system theme
   sets `.navigation-sidebar.background {{ color: … }}` concretely, and an
   inherited colour loses to it however the window above is styled. */
.hive-sidebar row,
.hive-sidebar label,
.hive-sidebar row label {{
  color: {text};
}}

.hive-sidebar row {{
  border-radius: 8px;
  margin: 1px 6px;
  min-height: 32px;
  transition: background-color {duration}ms ease-out;
}}

.hive-sidebar row:hover {{
  background-color: {surface0};
}}

.hive-sidebar row.hive-current {{
  background-color: {accent_soft};
  color: {text};
}}

.hive-sidebar row.hive-current image {{
  color: {accent};
}}

/* A pinned folder that is no longer on disk. Dimmed, never removed: the
   pinned list is the user's, and Hive does not edit it on their behalf. */
.hive-sidebar row.hive-missing label {{
  color: {overlay0};
  font-style: italic;
}}

.hive-sidebar row.hive-missing image {{
  color: {overlay0};
}}

/* Where a dragged folder would land. */
.hive-sidebar.hive-drop-active {{
  background-color: {surface0};
}}

/* The unpin menu on a pinned row. */
.hive-row-menu button {{
  min-width: 120px;
  padding: 4px 10px;
}}

/* Breadcrumb: flat segments, one accent at a time. */
.hive-breadcrumb button {{
  color: {subtext0};
  padding: 2px 8px;
  min-height: 26px;
  border-radius: 6px;
  background: none;
  box-shadow: none;
  border: none;
  font-weight: normal;
  transition: background-color {duration}ms ease-out;
}}

.hive-breadcrumb button:hover {{
  background-color: {surface0};
}}

.hive-breadcrumb button.hive-breadcrumb-current {{
  font-weight: bold;
  color: {text};
}}

.hive-breadcrumb .hive-breadcrumb-separator {{
  color: {overlay0};
  padding: 0 1px;
}}

/* File pane. Generous row padding, no grid lines. */
.hive-file-pane {{
  background-color: {base};
}}

.hive-file-pane listview > row,
.hive-file-pane columnview > listview > row {{
  padding: 2px 4px;
  min-height: 30px;
  border-radius: 6px;
  transition: background-color {duration}ms ease-out;
}}

.hive-file-pane row:hover {{
  background-color: {surface0};
}}

.hive-file-pane row:selected {{
  background-color: {accent_soft};
  color: {text};
}}

.hive-file-pane columnview > header > button {{
  background: none;
  box-shadow: none;
  border: none;
  color: {subtext0};
  font-size: 0.9em;
  padding: 4px 8px;
}}

.hive-file-pane columnview > header > button:hover {{
  background-color: {surface0};
}}

.hive-file-name {{
  color: {text};
}}

.hive-file-meta {{
  color: {subtext0};
  font-size: 0.9em;
}}

.hive-file-symlink {{
  font-style: italic;
  color: {subtext0};
}}

/* Grid view cells. */
.hive-file-pane gridview > child {{
  padding: 8px;
  border-radius: 8px;
  transition: background-color {duration}ms ease-out;
}}

.hive-file-pane gridview > child:hover {{
  background-color: {surface0};
}}

.hive-file-pane gridview > child:selected {{
  background-color: {accent_soft};
}}

/* Placeholder shown while a directory is still enumerating or is empty. */
.hive-placeholder {{
  color: {overlay1};
}}

.hive-placeholder-icon {{
  color: {surface2};
}}

/* Default folder and file icons stay monochrome; folder colors override. */
.hive-item-icon {{
  color: {subtext1};
}}

.hive-folder-icon {{
  color: {subtext1};
}}
",
        base = n.base.to_hex(),
        mantle = n.mantle.to_hex(),
        surface0 = n.surface0.to_hex(),
        surface2 = n.surface2.to_hex(),
        overlay0 = n.overlay0.to_hex(),
        overlay1 = n.overlay1.to_hex(),
        subtext0 = n.subtext0.to_hex(),
        subtext1 = n.subtext1.to_hex(),
        text = n.text.to_hex(),
        accent = accent.to_hex(),
        accent_soft = accent.to_rgba(if palette.dark { 0.26 } else { 0.22 }),
        duration = duration,
    );

    css.push_str("\n/* Folder colors: tint the symbolic icon only. */\n");
    for slot in Accent::ALL {
        let _ = writeln!(
            css,
            ".hive-folder-icon.{}{{color:{};}}",
            slot.css_class(),
            palette.accent(slot).to_hex()
        );
    }

    // The accent picker's swatches. Flat circles of the real colour, so the
    // choice is made against the palette that is actually loaded.
    let _ = write!(
        css,
        "
/* Accent swatches. */
.hive-swatch {{
  min-width: 24px;
  min-height: 24px;
  padding: 0;
  border-radius: 50%;
  background-image: none;
  box-shadow: none;
  border: 2px solid transparent;
  outline: none;
}}

.hive-swatch:hover {{
  border-color: {overlay1};
}}

/* Checked is the accent picker; focus is the folder-color grid, which is
   pressed rather than toggled and still has to show where the keyboard is. */
.hive-swatch:checked,
.hive-swatch:focus,
.hive-swatch:focus-visible {{
  border-color: {text};
}}
",
        overlay1 = n.overlay1.to_hex(),
        text = n.text.to_hex(),
    );

    for slot in Accent::ALL {
        let _ = writeln!(
            css,
            ".hive-swatch.{}{{background-color:{};}}",
            slot.css_class(),
            palette.accent(slot).to_hex()
        );
    }

    css
}

/// A readable foreground for `background`, for callers that tint outside CSS.
pub fn contrasting_text(palette: &Palette, background: Color) -> Color {
    palette.on_color(background)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::theme::catppuccin::{BUILT_IN, LATTE, MOCHA};

    fn opts(accent: Accent) -> StyleOptions {
        StyleOptions {
            accent,
            ..StyleOptions::default()
        }
    }

    #[test]
    fn braces_balance_for_every_flavor() {
        for palette in BUILT_IN {
            let css = generate(palette, &opts(Accent::Mauve));
            let opens = css.matches('{').count();
            let closes = css.matches('}').count();
            assert_eq!(opens, closes, "unbalanced braces in {}", palette.id);
            assert!(!css.contains("{{"), "unescaped brace in {}", palette.id);
            assert!(!css.contains("}}"), "unescaped brace in {}", palette.id);
        }
    }

    #[test]
    fn window_background_is_declared_directly_and_opaquely() {
        for palette in BUILT_IN {
            let css = generate(palette, &opts(Accent::Mauve));
            let expected = format!("background-color: {};", palette.neutrals.base.to_hex());
            assert!(
                css.contains("window.background") && css.contains(&expected),
                "{} lacks a direct opaque window background",
                palette.id
            );
        }
    }

    /// A hand-written system GTK theme paints widgets with literal colours and
    /// never reads libadwaita's custom properties, so Hive has to declare the
    /// same surfaces concretely. Setting only `--view-bg-color` left every
    /// light flavor half-applied: sidebar light, file pane still dark.
    #[test]
    fn view_surfaces_are_declared_concretely_for_every_flavor() {
        for palette in BUILT_IN {
            let css = generate(palette, &opts(Accent::Mauve));
            let base = palette.neutrals.base.to_hex();
            let text = palette.neutrals.text.to_hex();

            let block = block_containing(&css, ".view,").unwrap_or_else(|| {
                panic!("{} has no concrete .view rule", palette.id);
            });
            assert!(
                block.contains(&format!("background-color: {base};")),
                "{} .view background is not concrete: {block}",
                palette.id
            );
            assert!(
                block.contains(&format!("color: {text};")),
                "{} .view foreground is not concrete: {block}",
                palette.id
            );
        }
    }

    #[test]
    fn sidebar_text_colour_is_stated_not_inherited() {
        for palette in BUILT_IN {
            let css = generate(palette, &opts(Accent::Mauve));
            let text = palette.neutrals.text.to_hex();
            let block = block_containing(&css, ".hive-sidebar row,")
                .unwrap_or_else(|| panic!("{} has no sidebar text rule", palette.id));
            assert!(
                block.contains(&format!("color: {text};")),
                "{} sidebar text is not stated: {block}",
                palette.id
            );
        }
    }

    /// The declaration block of the first rule whose selector list starts with
    /// `selector`, so a test can assert about one rule rather than the file.
    fn block_containing<'a>(css: &'a str, selector: &str) -> Option<&'a str> {
        let start = css.find(selector)?;
        let open = css[start..].find('{')? + start;
        let close = css[open..].find('}')? + open;
        Some(&css[open..=close])
    }

    #[test]
    fn emits_custom_properties_not_only_define_color() {
        let css = generate(&MOCHA, &opts(Accent::Mauve));
        assert!(css.contains("--window-bg-color: #1e1e2e;"));
        assert!(css.contains("--sidebar-bg-color: #181825;"));
        assert!(css.contains("--view-bg-color: #1e1e2e;"));
        assert!(css.contains(":root {"));
    }

    #[test]
    fn accent_choice_drives_accent_properties() {
        let mauve = generate(&MOCHA, &opts(Accent::Mauve));
        let green = generate(&MOCHA, &opts(Accent::Green));
        assert!(mauve.contains("--accent-bg-color: #cba6f7;"));
        assert!(green.contains("--accent-bg-color: #a6e3a1;"));
        assert_ne!(mauve, green);
    }

    #[test]
    fn every_flavor_produces_distinct_output() {
        let sheets: Vec<String> = BUILT_IN
            .iter()
            .map(|p| generate(p, &opts(Accent::Mauve)))
            .collect();
        for (i, a) in sheets.iter().enumerate() {
            for b in sheets.iter().skip(i + 1) {
                assert_ne!(a, b);
            }
        }
    }

    #[test]
    fn all_fourteen_folder_classes_are_emitted() {
        let css = generate(&MOCHA, &opts(Accent::Mauve));
        for slot in Accent::ALL {
            let class = format!(".hive-folder-icon.hive-accent-{}", slot.id());
            assert!(css.contains(&class), "missing {class}");
        }
    }

    #[test]
    fn folder_colors_follow_the_active_flavor() {
        let mocha = generate(&MOCHA, &opts(Accent::Blue));
        let latte = generate(&LATTE, &opts(Accent::Blue));
        assert!(mocha.contains(".hive-folder-icon.hive-accent-mauve{color:#cba6f7;}"));
        assert!(latte.contains(".hive-folder-icon.hive-accent-mauve{color:#8839ef;}"));
    }

    #[test]
    fn every_accent_gets_a_swatch_in_the_active_flavor() {
        let mocha = generate(&MOCHA, &opts(Accent::Blue));
        let latte = generate(&LATTE, &opts(Accent::Blue));

        for slot in Accent::ALL {
            let class = format!(".hive-swatch.hive-accent-{}", slot.id());
            assert!(mocha.contains(&class), "{class} missing");
        }

        // The picker shows the colours of the flavor you are choosing within,
        // so the same slot is a different swatch in a different flavor.
        assert!(mocha.contains(".hive-swatch.hive-accent-mauve{background-color:#cba6f7;}"));
        assert!(latte.contains(".hive-swatch.hive-accent-mauve{background-color:#8839ef;}"));
    }

    #[test]
    fn compositor_owns_rounding_and_shadow_by_default() {
        let css = generate(&MOCHA, &StyleOptions::default());
        assert!(
            css.contains("window.csd"),
            "decoration block should be emitted"
        );
        assert!(css.contains("--window-radius: 0;"));

        let block = decoration_block(&css).expect("decoration block");
        assert!(block.contains("box-shadow: none;"), "{block}");
        assert!(block.contains("border-radius: 0;"), "{block}");

        let csd = generate(
            &MOCHA,
            &StyleOptions {
                client_side_rounding: true,
                client_side_shadow: true,
                ..StyleOptions::default()
            },
        );
        assert!(!csd.contains("--window-radius: 0;"));
        assert!(
            decoration_block(&csd).is_none(),
            "no decoration overrides when the client draws them"
        );
    }

    #[test]
    fn rounding_and_shadow_can_be_enabled_independently() {
        let shadow_only = generate(
            &MOCHA,
            &StyleOptions {
                client_side_shadow: true,
                ..StyleOptions::default()
            },
        );
        let block = decoration_block(&shadow_only).expect("decoration block");
        assert!(!block.contains("box-shadow"), "{block}");
        assert!(block.contains("border-radius: 0;"), "{block}");

        let rounding_only = generate(
            &MOCHA,
            &StyleOptions {
                client_side_rounding: true,
                ..StyleOptions::default()
            },
        );
        let block = decoration_block(&rounding_only).expect("decoration block");
        assert!(block.contains("box-shadow: none;"), "{block}");
        assert!(!block.contains("border-radius"), "{block}");
    }

    /// Extract the `window.csd { … }` rule body, if the generator emitted one.
    fn decoration_block(css: &str) -> Option<&str> {
        let start = css.find("window.csd")?;
        let open = css[start..].find('{')? + start;
        let close = css[open..].find('}')? + open;
        Some(&css[open + 1..close])
    }

    #[test]
    fn disabling_animations_zeroes_durations() {
        let on = generate(&MOCHA, &StyleOptions::default());
        assert!(on.contains("150ms"));

        let off = generate(
            &MOCHA,
            &StyleOptions {
                animations: false,
                ..StyleOptions::default()
            },
        );
        assert!(!off.contains("150ms"));
        assert!(off.contains("0ms"));
    }

    #[test]
    fn light_theme_gets_readable_accent_foreground() {
        use crate::theme::palette::contrast_ratio;

        let yellow = LATTE.accent(Accent::Yellow);
        let fg = LATTE.on_color(yellow);
        let css = generate(&LATTE, &opts(Accent::Yellow));
        assert!(css.contains(&format!("--accent-fg-color: {};", fg.to_hex())));

        assert!(
            contrast_ratio(fg, yellow) > contrast_ratio(LATTE.neutrals.base, yellow),
            "must beat the naive light-theme choice"
        );
        assert_eq!(fg, LATTE.neutrals.text, "the dark end of Latte's ramp");
    }

    #[test]
    fn dark_theme_gets_readable_accent_foreground() {
        use crate::theme::palette::contrast_ratio;

        let mauve = MOCHA.accent(Accent::Mauve);
        let fg = MOCHA.on_color(mauve);
        assert_eq!(fg, MOCHA.neutrals.crust, "dark text on a light accent");
        assert!(
            contrast_ratio(fg, mauve) > 4.5,
            "readable at body-text size"
        );
    }

    #[test]
    fn no_unresolved_format_placeholders_remain() {
        for palette in BUILT_IN {
            let css = generate(palette, &opts(Accent::Teal));
            assert!(
                !css.contains("{}"),
                "unfilled placeholder in {}",
                palette.id
            );
        }
    }

    #[test]
    fn contrasting_text_matches_palette_on_color() {
        let bg = MOCHA.accent(Accent::Peach);
        assert_eq!(contrasting_text(&MOCHA, bg), MOCHA.on_color(bg));
    }
}
